// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealEstateClassLibrary.DAL;

[Table("House")]
public partial class House
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Mode { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Location { get; set; }

    public int Size { get; set; }

    public int NoOfBeds { get; set; }

    public int NoOfBaths { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Image { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }
}